// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Construct Supabase URL from port if not explicitly set
const SUPABASE_API_PORT = import.meta.env.VITE_SUPABASE_API_PORT || import.meta.env.SUPABASE_API_PORT || '6010';
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || `http://127.0.0.1:${SUPABASE_API_PORT}`;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Debug: Log environment variables (remove in production)
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Missing Supabase environment variables:');
  console.error('  VITE_SUPABASE_URL:', SUPABASE_URL || 'UNDEFINED');
  console.error('  VITE_SUPABASE_ANON_KEY:', SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'UNDEFINED');
  console.error('  All VITE_ vars:', Object.keys(import.meta.env).filter(k => k.startsWith('VITE_')));
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'orch_flow'  // Orch-Flow uses orch_flow schema for all tables
  }
});